name: AI Code Review

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: review
        uses: ./.github/actions/reviewer
        with:
          api_key: ${{ secrets.LLM_PROVIDER_API_KEY  }}
          pr-title: ${{ github.event.pull_request.title }}
          pr-body: ${{ github.event.pull_request.body }}
          diff: ${{ steps.diff.outputs.value }}
